application:
  name: nexus
  createNamespace: ###ZARF_VAR_NEXUS_CREATE_NAMESPACE###
  namespace: nexus
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/nexus.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/packages/nexus versioning=loose registryUrl=https://repo1.dso.mil
    tag: 53.1.0-bb.1
  dependsOn:
    ###ZARF_VAR_NEXUS_DEPENDS_ON###
  baseValues:
    domain: bigbang.dev
    hostname: nexus
    istio:
      enabled: true
      injection: enabled
      nexus:
        gateways:
        - istio-system/tenant

     # When istio injected, add an annotation with the istio version to the manager pods only
    podAnnotations:
      bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###

    openshift: false

    image:
      pullPolicy: IfNotPresent

    job_image:
      pullPolicy: IfNotPresent

    monitoring:
      enabled: true
      serviceMonitor:
        createMetricsUser: true
        scheme: https
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
          insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target

    networkPolicies:
      enabled: true
      ingressLabels:
        app: null
        istio: null

    nexus:
      imagePullSecrets:
        - name: private-registry
      podAnnotations:
        bigbang.dev/istioVersion: 1.18.1-enterprise

    license_key: ""

